{
  config,
  pkgs,
  lib,
  ...
}: {
  # Symlink `functions` folder, but not the whole `fish` directory, as it
  # contains files generated by both Nix and Fish:
  xdg.configFile."fish/functions".source =
    config.lib.file.mkOutOfStoreSymlink
    "${config.home.sessionVariables.CFG}/.config/fish/functions";

  programs.fish = {
    enable = true;
    plugins = [
      {
        name = "foreign-env";
        src = pkgs.fishPlugins.foreign-env.src;
      }
      {
        name = "fish-theme-bobthefish";
        src = pkgs.fetchFromGitHub {
          owner = "oh-my-fish";
          repo = "theme-bobthefish";
          rev = "76cac812064fa749ffc258a20398c6f6250860c5";
          hash = "sha256-7nZ25R75WsSPqSmyeJbRQ49cITxL3D5CfyplsixFlY8=";
        };
      }
    ];

    shellInit = lib.optionalString pkgs.stdenv.isDarwin ''
      source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.fish
    '';

    interactiveShellInit = ''
      # bobthefish theme settings:
      set -g theme_newline_cursor yes
      set -g theme_date_format "+%H:%M:%S %F (%a)"
      set -g theme_color_scheme dark
      set -g theme_display_vi yes
      set -g theme_display_nix yes
      set -g theme_use_abbreviated_branch_name no
      set -g theme_display_git_master_branch yes
      set -g theme_prompt_prefix   '╭─'
      set -g theme_newline_prompt ' ╰─➤ '
      set -g theme_nerd_fonts yes

      set -g theme_display_node yes
    '';

    shellAbbrs = {
      # Basic
      l = "ls -lah";
      p = "pushd";
      po = "popd";

      # Direnv
      dea = "direnv allow .";
      ded = "direnv deny .";
      der = "direnv reload";

      # Git
      gs = "git status";

      gsh = "git show";
      gshr = "git show --color-words=\"[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+\"";

      gd = "git diff";
      gdr = "git diff --color-words=\"[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+\"";

      gdc = "git diff --staged";
      gdcr = "git diff --staged --color-words=\"[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+\"";

      ga = "git add";
      gap = "git add -p";
      gau = "git add -u";
      gai = "git add --intent-to-add";

      gcm = "git commit -m";
      gcma = "git commit --amend --no-edit";

      gpu = "git pull";

      gps = "git push -u (git-default-remote) HEAD";
      gpf = "git push --force";

      gco = "git checkout";
      gcb = "git checkout -b";

      gstaki = "git stash --keep-index --include-untracked";

      gspo = "git stash pop";
      gspu = "git stash --include-untracked; and git status";

      gbr = "git branch -a";

      glg = "git log";
      gl = "git lg";

      grb = "git rebase";
      grbc = "git rebase --continue";
      grbi = "git rebase -i";

      gchp = "git cherry-pick";
      gchpc = "git cherry-pick --continue";

      # Google Chrome aliases:
      igchr = "google-chrome --incognito & disown";
    };
  };
}
