{ config, ... }:
{
  # Symlink the whole .config/nvim directory:
  xdg.configFile.nvim.source = config.lib.file.mkOutOfStoreSymlink
    "${config.home.sessionVariables.CFG}/.config/nvim";

  # Symlink individual fish files (and not the whole directory, as it contains
  # files generated by fish):
  xdg.configFile."fish/aliases.fish".source = config.lib.file.mkOutOfStoreSymlink
    "${config.home.sessionVariables.CFG}/.config/fish/aliases.fish";

  xdg.configFile."fish/config.fish".source = config.lib.file.mkOutOfStoreSymlink
    "${config.home.sessionVariables.CFG}/.config/fish/config.fish";

  xdg.configFile."fish/functions".source = config.lib.file.mkOutOfStoreSymlink
    "${config.home.sessionVariables.CFG}/.config/fish/functions";
}
