# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/nix" =
    { device = "zfs_root/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/etc" =
    { device = "zfs_root/nixos/etc";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "zfs_root/nixos/var";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "zfs_root/nixos/var/lib";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" =
    { device = "zfs_root/nixos/var/lib/docker";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zfs_root/userdata/home";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4d3f92db-47ea-49cd-8ab5-63cb17e8613b"; }
    ];

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.video.hidpi.enable = lib.mkDefault true;
}
